# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e0e2eb5f34ee5e7d3dfc254661f3ba4fdde487dd6a3d15f4c87f1d046dca5beddfb280f317c479adbeb6b2643aa7c17bd4df193c4fa44a8941237f35ea2226e7

test:
  secret_key_base: 2a513ab004d8dc3dd1c8e1482cb7bd5eeeba101743c59086b436aad56e6e411c487a9f90e35d416f226a7a5f21b3a74cfdb7103c3084217ba7544d2db75b926d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
