# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d0d41480f60c0263ff566cd2a0f4e2d5a7e2710679008b64e07d73848e29571b2ee2a69d72af6c2cbe11b4622a2398ae4bee37825a8c159e44689281479a136

test:
  secret_key_base: a1c33ba3ec3e4ffa208e640987ca7f8ef835ce2bc10d3b2950dc56cd4545c4fe1e90e2d720c2f1560f1a3df8a3ca469081ed652aa99699767e2d6b494d628069

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: f13c0db2b81b9f9bfe7a51092025d7ebe59199aa5a182a7b6746161725cd7486603104f0ff7524c24adeb2c7a8e04d64c4242289043c0d6bbb6d4ecf0254b7b9
